# Generated by Django 5.2.7 on 2025-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowbalancerule',
            name='last_low_balance_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
