# Generated by Django 5.2.7 on 2025-11-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lowbalancerule_last_low_balance_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('LOW_BALANCE', 'Low balance'), ('DEPOSIT_CONFIRMED', 'Deposit confirmed'), ('WITHDRAW_ALERT', 'Withdraw alert'), ('DEVICE_EVENT', 'Device event'), ('NEW_USER', 'New user registered'), ('USER_APPROVAL_REQUIRED', 'User approval required'), ('USER_BLOCKED', 'User blocked'), ('PASSWORD_RESET', 'Password reset')], max_length=32),
        ),
    ]
