# Generated by Django 5.2.7 on 2025-10-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
