# Generated by Django 4.2 on 2025-11-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_transactionflag_reportnote_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionflag',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
