# Generated by Django 4.2 on 2025-11-13 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_analysis', '0003_transactionflag_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='admin_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transactionflag',
            name='analysis_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='ai_analysis.analysisreport'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='anomalies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='clusters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('freeze_user', 'freeze_user'), ('unfreeze_user', 'unfreeze_user'), ('flag_transaction', 'flag_transaction'), ('resolve_flag', 'resolve_flag'), ('add_note', 'add_note'), ('export_report', 'export_report')], max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
