# Generated by Django 4.2 on 2025-11-19 09:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee charged for this transfer.', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount delivered to recipient (after fee logic).', max_digits=18)),
                ('from_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('from_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('to_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('to_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['created_by'], name='peer_transa_created_526ade_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_user'], name='peer_transa_to_user_3ed60b_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='peer_transa_status_9db2f9_idx'),
        ),
    ]
