"""
Django settings for savings_api project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decimal import Decimal
import dj_database_url

PEER_TRANSACTIONS_FEE_PERCENT = Decimal("0.10")  # 10% default
# Optional: set to an existing user id to receive fees
PEER_TRANSACTIONS_FEE_ACCOUNT_ID = None  # e.g. 1

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-as1nxm@b*&339*hakqgj0hepa=p#=fkqxq163*!!ch8p+t@pn8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com", 
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Local Apps
    'core',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.humanize',
    'chatbot',
    'chatterbot.ext.django_chatterbot', 
    'ai_analysis',
    'peer_transactions',
    'ai_assistant',
    'feedback',
]

MIDDLEWARE = [
    #Added Middleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'savings_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'savings_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": {
        # Local dev default (your existing local DB)
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("LOCAL_DB_NAME", "savings_db"),
        "USER": os.environ.get("LOCAL_DB_USER", "savings_user"),
        "PASSWORD": os.environ.get("LOCAL_DB_PASSWORD", "savings_pass"),
        "HOST": os.environ.get("LOCAL_DB_HOST", "localhost"),
        "PORT": os.environ.get("LOCAL_DB_PORT", "5433"),
    }
}

# On Render: override with DATABASE_URL if present
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=True,  # Render Postgres uses SSL
    )



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = 'static/'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- REST framework + Simple JWT config: add near bottom of file ---

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
     "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "600/min",
        "otp": "5/min",
        "login": "10/min",
    },
    
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

from corsheaders.defaults import default_headers, default_methods

CORS_ALLOW_ALL_ORIGINS = True  # good for production


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    'http://192.168.1.68:19006',  # Expo web/devtools if needed
    'exp://192.168.1.68:19000', 
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "content-type",
    "x-requested-with",
]
# ✅ Allow ALL deployments of this project on Vercel:
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://savings-management-frontend.*\.vercel\.app$",
]

CORS_ALLOW_METHODS = list(default_methods)  # GET, POST, OPTIONS, etc.
# Optionally restrict to:
# CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.vercel.app",
    # "https://creditjambo-backend.fly.dev",
    "https://*.onrender.com",
]


# --- custom user model ---
AUTH_USER_MODEL = "core.User"

# DEV: prints emails to console
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "daniel.mubu21@gmail.com"        # 👈 your Gmail or custom email
EMAIL_HOST_PASSWORD = "cyzwwiettfpxwsuc"      # 👈 not your Gmail password!
DEFAULT_FROM_EMAIL = "SavingDm <no-reply@creditjambo.com>"

# use PBKDF2 with SHA-512 as required by the brief
PASSWORD_HASHERS = [
    "savings_api.hashers.PBKDF2SHA512PasswordHasher",  # <-- replace 'project' with your project package
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",  # fallback
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Optional: configure ChatterBot storage if desired
CHATTERBOT = {
    'name': 'MyDjangoBot',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'storage_adapter': 'chatterbot.storage.SQLStorageAdapter',
}   

LOW_BALANCE_THRESHOLD = 50.00

# VAPID keys — generate once (instructions below)
VAPID_PUBLIC_KEY = "<paste_public_vapid_here>"
VAPID_PRIVATE_KEY = "<paste_private_vapid_here>"
VAPID_CLAIMS = {"sub": "mailto:noreply@example.com"}

# Optional: whether to actually send push in dev (sync)
SEND_WEBPUSH_NOTIFICATIONS = False

# Firebase Cloud Messaging (FCM)
SEND_FCM_NOTIFICATIONS = True
FCM_SERVER_KEY = "<YOUR_FIREBASE_SERVER_KEY>"

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


PEER_TRANSACTIONS_FEE_ACCOUNT_USERNAME = "saving_fee"
PEER_TRANSACTIONS_FEE_PERCENT = Decimal("0.10")  # optional, default is 10%


# AI / Ollama settings (settings.py)
AI_ASSISTANT_USE_OLLAMA = True
OLLAMA_API_URL = "http://localhost:11434"       # default Ollama HTTP API
OLLAMA_MODEL_NAME = "llama2:latest"             # use the model you pulled
AI_ASSISTANT_OLLAMA_TIMEOUT = 60                # seconds
AI_ASSISTANT_HISTORY_WINDOW = 30                # messages to include in history
